# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list
- type: webfuzzsub
  options:
    url: https://github.com/freefq/free
- type: webfuzzsub
  options:
    url: https://uploader.shimo.im/f/w4fhn48OhKfxIcsA.txt?attname=tt.txt
- type: webfuzzsub
  options:
    url: https://github.com/pojiezhiyuanjun/freev2
- type: webfuzzsub
  options:
    url: https://wechoice.ml/main.html
- type: webfuzzsub
  options:
    url: https://i.sqeven.me/q/detail/100
# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray
- type: subscribe
  options:
    url: https://iwxf.netlify.app/
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/umelabs/node.umelabs.dev/master/Subscribe/SSR.md
- type: subscribe
  options:
    url: https://gitea.com/proxypools/sub/raw/branch/main/clash/clash.yaml
- type: subscribe
  options:
    url: https://gitea.com/proxypools/sub/raw/branch/main/clash/clashr.yaml
- type: subscribe
  options:
    url: https://gitea.com/proxypools/sub/raw/branch/main/ss/ss.txt

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://i.sqeven.me/discuss/detail/100
- type: webfuzz
  options:
    url: https://i.sqeven.me/discuss/detail/102
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html
- type: webfuzz
  options:
    url: https://lisondawang.tk/jiedianfenxiang.html
- type: webfuzz
  options:
    url: https://github.com/freefq/free
- type: webfuzz
  options:
    url: https://github.com/JACKUSR2089/v2ray-subscribed
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/ruanfei/ShadowsocksRRShare/master/ss/ss.txt
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/ruanfei/ShadowsocksRRShare/master/ssr/ssr.txt

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200
- type: tgchannel
  options:
    channel: aifenxiang2020
    num: 200
- type: tgchannel
  options:
    channel: sharecentre
    num: 200
- type: tgchannel
  options:
    channel: SSRSUB
    num: 200
- type: tgchannel
  options:
    channel: FreeSSRNode
    num: 200
- type: tgchannel
  options:
    channel: fanqiang666
    num: 200
- type: tgchannel
  options:
    channel: ssrtool_crack
    num: 200
- type: tgchannel
  options:
    channel: ssrv2taytgshare
    num: 200
- type: tgchannel
  options:
    channel: VPNFolder
    num: 200
- type: tgchannel
  options:
    channel: baipiaofuli

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum.php?mod=rss&fid=50&auth=0
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum.php?mod=rss&fid=36&auth=0
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum.php?mod=rss&fid=2&auth=0
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum.php?mod=rss&fid=51&auth=0
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum.php?mod=rss&fid=48&auth=0
    
# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml

# 某个网站抓取
- type: web-freessrxyz
  options:
    url: https://lightyearapp.life/zh/free-vpn
