# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list
- type: webfuzzsub
  options:
    url: https://github.com/pojiezhiyuanjun/freev2
- type: webfuzzsub
  options:
    url: https://wechoice.ml/main.html

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray
- type: subscribe
  options:
    url: https://iwxf.netlify.app/
- type: subscribe
  options:
    url: https://gitea.com/proxypools/sub/raw/branch/main/clash/clash.yaml
- type: subscribe
  options:
    url: https://gitea.com/proxypools/sub/raw/branch/main/ss/ss.txt

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200
- type: tgchannel
  options:
    channel: ssrtool_crack
    num: 200
- type: tgchannel
  options:
    channel: VPNFolder
    num: 200
- type: tgchannel
  options:
    channel: proxypools

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum.php?mod=rss&fid=50&auth=0
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum.php?mod=rss&fid=36&auth=0
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum.php?mod=rss&fid=2&auth=0
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum.php?mod=rss&fid=51&auth=0

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml

# 某个网站抓取
- type: web-freessrxyz
  options:
    url: https://lightyearapp.life/zh/free-vpn
